# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 05:02
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='na', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
