# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20170818_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
