# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Transformation Title')),
                ('description', models.TextField(verbose_name='High-Level Description')),
                ('problem', models.TextField(blank=True, verbose_name='What problem is it trying to solve?')),
                ('specific_orgs', models.CharField(blank=True, max_length=240, verbose_name='Which specific areas or other organizations are involved?')),
                ('primary_contact', models.CharField(blank=True, max_length=100, verbose_name='Primary Contact')),
                ('ministry', models.ManyToManyField(to='transformations.Ministry')),
            ],
        ),
    ]
