# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 19:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import transformations.models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give this resource a descriptive name.', max_length=50, verbose_name='Title')),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=20)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('resource', models.FileField(upload_to=transformations.models.Attachment.get_upload_path, verbose_name='Attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give this resource a descriptive name.', max_length=50, verbose_name='Title')),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=20)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('resource', models.URLField(verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['abbrev']},
        ),
        migrations.AddField(
            model_name='transformation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transformation',
            name='category',
            field=models.CharField(blank=True, choices=[('structure', 'Structure/Process'), ('strategy', 'Strategy/Policy'), ('service', 'Service Delivery'), ('people', 'People Development'), ('all', 'All of the Above')], max_length=20),
        ),
        migrations.AddField(
            model_name='transformation',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='n/a', editable=False, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformation',
            name='status',
            field=models.CharField(blank=True, choices=[('direction', 'Defining Direction'), ('design', 'Design Stage'), ('implementation', 'Implementation'), ('sustainment', 'Sustainment'), ('complete', 'Past Transformation')], max_length=20),
        ),
        migrations.AddField(
            model_name='link',
            name='transformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='transformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
    ]
