# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0002_auto_20170807_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transformation_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transformation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='transformations.Transformation_Tag'),
        ),
    ]
