# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0003_auto_20170807_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource_tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transformation_tag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='tags',
        ),
        migrations.AddField(
            model_name='attachment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='transformations.Resource_Tag'),
        ),
        migrations.RemoveField(
            model_name='link',
            name='tags',
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, to='transformations.Resource_Tag'),
        ),
    ]
