# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0004_auto_20170807_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='transformation',
        ),
        migrations.RemoveField(
            model_name='link',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='link',
            name='transformation',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Resource_Tag',
        ),
    ]
