# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0005_auto_20170809_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transformation',
            options={'ordering': ['-date_modified']},
        ),
        migrations.AddField(
            model_name='transformation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
