# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0006_auto_20170810_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='category',
            field=models.CharField(blank=True, choices=[('structure', 'Structure/Process'), ('strategy', 'Strategy/Policy'), ('service', 'Service Delivery'), ('people', 'People Development'), ('all', "'All of the Above'")], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='problem',
            field=models.TextField(blank=True, verbose_name='Core Problem'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='specific_orgs',
            field=models.CharField(blank=True, max_length=240, verbose_name='Specific Orgs'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='status',
            field=models.CharField(blank=True, choices=[('prospective', 'Prospective'), ('ongoing', 'Ongoing'), ('complete', 'Past/Complete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='transformations.Transformation_Tag', verbose_name='Areas of Focus'),
        ),
    ]
