# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0007_auto_20170916_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='ministry',
            field=models.ManyToManyField(related_name='transformations', to='transformations.Ministry'),
        ),
    ]
