# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0008_auto_20171011_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='abbrev',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
