# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transformations', '0006_auto_20170810_0103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to=people.models.Profile.get_upload_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Ministry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
