# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 03:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
