# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170824_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ministry',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='transformations.Ministry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, default='asdf', max_length=200),
            preserve_default=False,
        ),
    ]
