# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170825_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Ministry'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=people.models.Profile.get_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
