# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_action'),
        ('people', '0005_auto_20170825_0922'),
    ]

    operations = [
    ]
