# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20170825_0922'),
        ('people', '0005_action'),
    ]

    operations = [
    ]
