# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_merge_20170907_2152'),
        ('people', '0006_merge_20170827_1354'),
    ]

    operations = [
    ]
