# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 03:25
from __future__ import unicode_literals

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import resources.models


class Migration(migrations.Migration):

    replaces = [('resources', '0001_initial'), ('resources', '0002_auto_20170815_1620'), ('resources', '0003_auto_20170816_1252'), ('resources', '0004_auto_20170817_0127'), ('resources', '0005_auto_20170818_1333'), ('resources', '0006_auto_20170818_1342'), ('resources', '0007_auto_20170818_1342'), ('resources', '0008_auto_20170818_1345'), ('resources', '0009_auto_20170819_2256'), ('resources', '0010_auto_20170820_1003'), ('resources', '0011_auto_20170820_1035'), ('resources', '0012_auto_20170820_2246'), ('resources', '0013_auto_20170824_1603'), ('resources', '0014_auto_20170907_2151'), ('resources', '0015_auto_20170907_2200'), ('resources', '0016_auto_20170907_2210'), ('resources', '0017_auto_20170909_2043'), ('resources', '0018_auto_20170909_2048'), ('resources', '0019_auto_20170916_2043'), ('resources', '0020_auto_20170917_2108')]

    initial = True

    dependencies = [
        ('topics', '0005_auto_20170818_2238'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transformations', '0006_auto_20170810_0103'),
        ('transformations', '0005_auto_20170809_2330'),
        ('topics', '0004_auto_20170815_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('file', 'File'), ('link', 'Link')], max_length=5, verbose_name='Resource Type')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Describe the resource and how it may be useful to others.')),
                ('slug', autoslug.fields.AutoSlugField()),
                ('file', models.FileField(blank=True, null=True, upload_to=resources.models.Resource.get_upload_path, verbose_name='Attachment')),
                ('link', models.URLField(blank=True, help_text="The URL (address), starting with 'http.'", null=True, verbose_name='Link')),
                ('category', models.CharField(choices=[('example', 'Real World Example'), ('template', 'Tool or Template'), ('reading', 'Theory, Guide, Article or Book'), ('lessons', 'Lessons Learned')], max_length=10, verbose_name='Resource Category')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topics', mptt.fields.TreeManyToManyField(blank=True, help_text='Ctrl-click to choose all that apply.', null=True, to='topics.Topic')),
                ('transformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('resources.resource',),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=resources.models.Resource.get_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topics',
            field=mptt.fields.TreeManyToManyField(blank=True, help_text='Ctrl-click to choose all that apply.', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('resources.resource',),
        ),
        migrations.AddField(
            model_name='resource',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Type your post here.', null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('post', 'Post')], max_length=5, verbose_name='Resource Type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(help_text='Describe the resource and how it may be useful to others.', max_length=255),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(2, 'Really Great'), (1, 'Great'), (0, 'Interesting')], default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Your Rating')),
                ('review', models.TextField(blank=True, help_text="What's valuable about this resource?", null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resources.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('user', 'resource')]),
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_modified']},
        ),
        migrations.AddField(
            model_name='resource',
            name='credit',
            field=models.CharField(blank=True, help_text='Who made or contributed to this?', max_length=100, null=True, verbose_name='Credit'),
        ),
    ]
