# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transformations', '0005_auto_20170809_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give this resource a descriptive name.', max_length=50, verbose_name='Title')),
                ('description', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                #('resource', models.FileField(upload_to=resources.models.Attachment.get_upload_path, verbose_name='Attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give this resource a descriptive name.', max_length=50, verbose_name='Title')),
                ('description', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('resource', models.URLField(verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, to='resources.Resource_Tag'),
        ),
        migrations.AddField(
            model_name='link',
            name='transformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='resources.Resource_Tag'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='transformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
    ]
