# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 20:20
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20170815_1330'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='topics',
            field=mptt.fields.TreeManyToManyField(blank=True, to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='link',
            name='topics',
            field=mptt.fields.TreeManyToManyField(blank=True, to='topics.Topic'),
        ),
    ]
