# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20170815_1620'),
    ]

    operations = [
        # NB Had to hide these next two pieces because my first migration went awry. If something goes wrong, look here.
        migrations.RemoveField(
            model_name='attachment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='link',
            name='tags',
        ),
        migrations.AddField(
            model_name='attachment',
            name='category',
            field=models.CharField(choices=[('example', 'Templates, Tools and Exampples'), ('reading', 'Guides, Articles, Books and other Reference'), ('lessons', 'Lessons Learned / Your Perspective')], default='reading', max_length=10, verbose_name='Primary Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.CharField(choices=[('example', 'Templates, Tools and Exampples'), ('reading', 'Guides, Articles, Books and other Reference'), ('lessons', 'Lessons Learned / Your Perspective')], default='reading', max_length=10, verbose_name='Primary Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='topics',
            field=mptt.fields.TreeManyToManyField(blank=True, help_text='Ctrl-click to choose all that apply.', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='link',
            name='topics',
            field=mptt.fields.TreeManyToManyField(blank=True, help_text='Ctrl-click to choose all that apply.', to='topics.Topic'),
        ),
    ]
