# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20170816_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='category',
            field=models.CharField(choices=[('example', 'Templates, Tools and Examples'), ('reading', 'Guides, Articles, Books and other Reference'), ('lessons', 'Lessons Learned from Real Experience')], max_length=10, verbose_name='Resource Category'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(help_text='Describe the resource and how it may be useful to others.'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='transformation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.CharField(choices=[('example', 'Templates, Tools and Examples'), ('reading', 'Guides, Articles, Books and other Reference'), ('lessons', 'Lessons Learned from Real Experience')], max_length=10, verbose_name='Resource Category'),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(help_text='Describe the resource and how it may be useful to others.'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='link',
            name='transformation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
    ]
