# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20170817_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='resource',
            field=models.URLField(help_text="The URL (address), starting with 'http.'", verbose_name='Link'),
        ),
    ]
