# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20170818_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='transformation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='transformation',
            field=models.CharField(max_length=100),
        ),
    ]
