# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20170818_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='transformation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
        migrations.AlterField(
            model_name='link',
            name='transformation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
    ]
