# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 02:56
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0006_auto_20170810_0103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0005_auto_20170818_2238'),
        ('resources', '0008_auto_20170818_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('file', 'File'), ('link', 'Link')], max_length=5, verbose_name='Resource Type')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Describe the resource and how it may be useful to others.')),
                ('slug', autoslug.fields.AutoSlugField()),
                ('file', models.FileField(blank=True, null=True, upload_to=resources.models.Resource.get_upload_path, verbose_name='Attachment')),
                ('link', models.URLField(blank=True, help_text="The URL (address), starting with 'http.'", null=True, verbose_name='Link')),
                ('category', models.CharField(choices=[('example', 'Real World Example'), ('template', 'Tool or Template'), ('reading', 'Theory, Guide, Article or Book'), ('lessons', 'Lessons Learned')], max_length=10, verbose_name='Resource Category')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topics', mptt.fields.TreeManyToManyField(blank=True, help_text='Ctrl-click to choose all that apply.', null=True, to='topics.Topic')),
                ('transformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='transformation',
        ),
        migrations.RemoveField(
            model_name='link',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='link',
            name='transformation',
        ),
        migrations.DeleteModel(
            name='Resource_Tag',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('resources.resource',),
        ),
    ]
