# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import mptt.fields
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20170819_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=resources.models.Resource.get_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topics',
            field=mptt.fields.TreeManyToManyField(blank=True, help_text='Ctrl-click to choose all that apply.', to='topics.Topic'),
        ),
    ]
