# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 14:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20170820_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
