# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_auto_20170907_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(help_text='Describe the resource and how it may be useful to others.', max_length=255),
        ),
    ]
