# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 02:10
from __future__ import unicode_literals

from django.db import migrations, models
#import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_auto_20170907_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='post',
            field=models.TextField(blank=True, help_text='Type your post here.', null=True, verbose_name='Post'),
        ),
    ]

# Cheated here and removed references to tinymce