# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 00:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_auto_20170907_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Type your post here.', null=True, verbose_name='Post'),
        ),
    ]
