# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 00:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_auto_20170909_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Type your post here.', null=True, verbose_name='Post'),
        ),
    ]
